apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-url-shortener
  labels:
    app: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: go-url-shortener
          image: localhost:5000/go-url-shortener:0.1.1
          