apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-url-shortener
  labels:
    app: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 5
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: go-url-shortener
          image: localhost:5000/go-url-shortener:0.3.1
          ports:
            - containerPort: 9000
          env:
            - name: URL_SHORTENER_FAIL_PERCENT
              valueFrom:
                configMapKeyRef:
                  name: url-shortener-config
                  key: fail_percent
            - name: URL_SHORTENER_REDIS_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: url-shortener-config
                  key: redis_addresses
            - name: URL_SHORTENER_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortener-redis-cluster-secret
                  key: password

          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 10
            failureThreshold: 1
          