apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-urls-holder
spec:
  selector:
    matchLabels:
      app: redis-urls-holder
  template:
    metadata:
      labels:
        app: redis-urls-holder
    spec:
      containers:
        - name: redis-urls-holder
          image: redis
          ports:
            - containerPort: 6379