apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-url-shortener
  labels:
    app: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: go-url-shortener
          image: localhost:5000/go-url-shortener:0.2.0
          ports:
            - containerPort: 9000
          env:
            - name: URL_SHORTENER_REDIS_ADDRESS
              value: "redis-urls-holder:6379"
          