apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-url-shortener-canary
  labels:
    app: url-shortener
    release: canary
spec:
  selector:
    matchLabels:
      app: url-shortener
      release: canary
  replicas: 1
  template:
    metadata:
      labels:
        app: url-shortener
        release: canary
    spec:
      containers:
        - name: go-url-shortener
          image: localhost:5000/go-url-shortener:0.2.1
          ports:
            - containerPort: 9000
          env:
            - name: URL_SHORTENER_REDIS_ADDRESS
              value: "redis-urls-holder:6379"
            - name: URL_SHORTENER_FAIL_PERCENT
              value: "75"
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 10
            failureThreshold: 4
          